'use strict';

const express = require('express');
const app = express();
const jokes = require('server/routes/jokes.api');
const swagger = require('swagger-jsdoc');
const swagger_ui = require('swagger-ui-express')

/**
 * Set up API documentation generator
 * API documentation has been automatically generated by swagger-ui-express and the swagger-jsdoc npm packages
 */
const definition = {
    openapi: '3.0.0',
    info: {
        title: "API documentation for Punchline API",
        version: '1.0.0'
    },
};

const options = {
    definition,
    apis: [
        './server/routes/*.js',
    ]
}

const swagger_spec = swagger(options)

app.use(express.static(__dirname + '/client'));

app.get('/', (req, res) => {
    res.sendFile('index.html');
});

app.use('/docs', swagger_ui.serve, swagger_ui.setup(swagger_spec));

/* 
 * API endpoints for the jokes API
 */

app.use('/api/jokes', jokes)

app.listen(process.env.PORT);